### PR TITLE
📂 o+x for directories

### PR DESCRIPTION
**Pull request by database64128**
Tested and works.

### CODE REVIEW

**Comment by mzz2017** [comment]
Thanks for your work

**Comment by database64128** [comment]
By the way, according to the docs, `pyinotify`'s event system has `event.dir` that indicates whether the path that triggered the event is a directory. But I'm not touching anything related to `pyinotify` because it's not available on Windows. On Windows VSCode can't auto-complete anything related to the package, and keeps giving me errors for the missing import.

**Comment by mzz2017** [comment]
I know this, but I think the implementation now is okey.

**Comment by mzz2017** [comment]
Python is a glue language and we could not focus on the performance and code elegance.

"working is fine"

**Pull request merged**
