### PR TITLE
📂 o+x for directories

### PR DESCRIPTION
**Pull request by database64128**
Please review carefully, as I'm not at all familiar with Python. 😅

### CODE REVIEW

**Review by mzz2017 — APPROVED** [review]
LGTM.
Have you verified its feasibility?

**Comment by mzz2017** [comment]
I think there is no problem.
I am merging it.

**Comment by database64128** [comment]
Actually there is a problem. I got mixed up between the `stat` package and `os.stat`. Can you reset the main branch to 4bb5d32, so I can create a new pull request with the patch I just tested that actually works?

**Comment by mzz2017** [comment]
And.. I am not a skilled pythonor too.

**Pull request merged**
